<?php
/**
 * @package AayushPlugin
 * Plugin Name: Aayush Practice Plugin
 * Plugin URI: http://aayushali.com.np/plugin
 * Description: This is my first attempt on writing a custom plugin.
 * Version: 1.0.0
 * Author: Aayush Ali
 * Author URI: https://aayushali.com.np
 * License: GPLv2 or later
 * Text Domain: aayush-plugin
 */
//These three works as same
/*if (!defined( 'ABSPATH' )){
    die;
}

*/
defined('ABSPATH') or die('Hey, you can/t access this file, you silly human!');
/*if (! function_exists('add_action')){
    echo 'Hey, you can\t access this file, you silly human!';
    exit;
}*/
// checking for the autoload file which is autogenerated by composer.json file
// refer composer.json and see the the key autoload
if (file_exists(dirname(__FILE__) . '/vendor/autoload.php')) {
    require_once dirname(__FILE__) . '/vendor/autoload.php';
}

function activate_aayush_plugin()
{
    Inc\Base\Activate::activate();
}

register_activation_hook(__FILE__, 'activate_aayush_plugin');
function deactivate_aayush_plugin()
{
    Inc\Base\Deactivate::deactivate();
}

register_deactivation_hook(__FILE__, 'deactivate_aayush_plugin');
if (class_exists('Inc\\Init')) {
    Inc\Init::register_services();
}